### ISSUE TITLE
\sigma used as canonical coherence iso

### ISSUE THREAD

**Issue by dspivak** [dspivak/supply#1]
In the document, \sigma is defined as a certain kind of isomorphism coming from rearranging the order of two indexed tensors. But Tobias points out in a July 2 email that in the proof of the main theorem, we seem to use \sigma as the generic Mac Lane coherence isomorphism.

I think it would be best to *just* use \sigma to mean the generic Mac Lane coherence isomorphism, not waste time with the rearranging indexed tensors stuff. Make sure that works, and that the proof of the main theorem is correct.

**Comment by brendanfong** [comment]
looks like this was addressed before first arXiv version
